/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;
import static com.sun.javafx.fxml.expression.Expression.not;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import static java.awt.PageAttributes.MediaType.D;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Locale;
import static javafx.beans.binding.Bindings.not;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 * 
 */
public class katalog extends javax.swing.JFrame {
   DefaultTableModel model;
    
String pilihan ="";
String pilihan2 ="";
int kode_barang;
int jumlah_barang;
int harga_barang;
int bayarbrg ,beli ,harga;
int kodbar;
int ukuran;
String setkode;
    

    /**
     * Creates new form katalog
     */

   private static String nama;
   public katalog(String username) {
    initComponents();
    nama=username;
    nisa.setText("Hai"+" "+nama+" "+"!");
    
    
    this.setTitle("Menu");
    this.setLocationRelativeTo(this);    
     
    
   
}
    katalog() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Katalog = new javax.swing.JButton();
        Kasir = new javax.swing.JButton();
        Laporan = new javax.swing.JButton();
        Tentang = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        Nota = new javax.swing.JButton();
        mainpanel = new javax.swing.JPanel();
        javax.swing.JPanel kata = new javax.swing.JPanel();
        javax.swing.JLabel hai = new javax.swing.JLabel();
        nisa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        kat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        kasir = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbpcs = new javax.swing.JComboBox<>();
        cbukuran = new javax.swing.JComboBox<>();
        txtharga = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        cbkode = new javax.swing.JComboBox<>();
        tambah2 = new javax.swing.JButton();
        table = new javax.swing.JButton();
        txtkode = new javax.swing.JTextField();
        txtukuran = new javax.swing.JTextField();
        nott = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtbayar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtk = new javax.swing.JTextField();
        Refresh = new javax.swing.JButton();
        txtkembali = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lap = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        object1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        nota = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/PicsArt_07-25-09.00.23_resize_88_resize_65.png"))); // NOI18N

        Katalog.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Katalog.setText("Katalog");
        Katalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KatalogActionPerformed(evt);
            }
        });

        Kasir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Kasir.setText("Kasir");
        Kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KasirActionPerformed(evt);
            }
        });

        Laporan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Laporan.setText("Laporan");
        Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanActionPerformed(evt);
            }
        });

        Tentang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Tentang.setText("About");
        Tentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TentangActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        Nota.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Nota.setText("Nota");
        Nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Tentang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Katalog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Kasir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(16, 16, 16))
                                    .addComponent(Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(EXIT)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Katalog)
                .addGap(18, 18, 18)
                .addComponent(Kasir)
                .addGap(18, 18, 18)
                .addComponent(Laporan)
                .addGap(15, 15, 15)
                .addComponent(Nota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tentang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXIT)
                .addGap(23, 23, 23))
        );

        mainpanel.setBackground(new java.awt.Color(255, 102, 0));
        mainpanel.setLayout(new java.awt.CardLayout());

        kata.setBackground(new java.awt.Color(255, 102, 0));
        kata.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hai.setFont(new java.awt.Font("CentSchbkCyrill BT", 3, 36)); // NOI18N
        hai.setText("Tidak Ada Urusan Dunia Yang Sulit ");
        kata.add(hai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        nisa.setFont(new java.awt.Font("CentSchbkCyrill BT", 3, 36)); // NOI18N
        nisa.setText("Hai !");
        kata.add(nisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel23.setFont(new java.awt.Font("CentSchbkCyrill BT", 3, 36)); // NOI18N
        jLabel23.setText("Jika Kamu Pandai Bersyukur");
        kata.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 278, -1, -1));

        mainpanel.add(kata, "card5");

        kat.setBackground(new java.awt.Color(255, 102, 0));
        kat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        kat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 184, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("Katalognya ya!");
        kat.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 31, 388, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Katalog3.jpg"))); // NOI18N
        kat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Katalog4.jpg"))); // NOI18N
        kat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 125, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Katalog5.jpg"))); // NOI18N
        kat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 125, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Katalog6.jpg"))); // NOI18N
        kat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 125, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/Katalog7.jpg"))); // NOI18N
        kat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/katalog10.jpg"))); // NOI18N
        kat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/katalog12.jpg"))); // NOI18N
        kat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/katalog8.jpg"))); // NOI18N
        kat.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        jButton10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton10.setText("Mulai");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        kat.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        mainpanel.add(kat, "card2");

        kasir.setBackground(new java.awt.Color(255, 102, 0));
        kasir.setPreferredSize(new java.awt.Dimension(1006, 641));
        kasir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel12.setText("Jangan Lupa Bayar ya!");
        kasir.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));
        jLabel12.getAccessibleContext().setAccessibleName("Jangan Lupa Bayar!");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setText("Kode barang :");
        kasir.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, 30));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("Jumlah :");
        kasir.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Ukuran :");
        kasir.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Harga :");
        kasir.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        cbpcs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PCS-", "1", "2", "3", "4", "5" }));
        cbpcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpcsActionPerformed(evt);
            }
        });
        kasir.add(cbpcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 60, 30));

        cbukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UK", "XS", "S", "M", "L", "XL" }));
        cbukuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbukuranActionPerformed(evt);
            }
        });
        kasir.add(cbukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 60, 30));

        txtharga.setEditable(false);
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        kasir.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 30));

        txtjumlah.setEditable(false);
        txtjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahActionPerformed(evt);
            }
        });
        kasir.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 90, 30));

        cbkode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KODE", "Nb A48D", "Nb A48A", "Nb A49A", "Nb A49M", "Nb A50M", "Nb A46K", "Na 40C", "Na 40A" }));
        cbkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkodeActionPerformed(evt);
            }
        });
        kasir.add(cbkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 60, 30));

        tambah2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        tambah2.setText("Hitung Harga");
        tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah2ActionPerformed(evt);
            }
        });
        kasir.add(tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 180, 40));

        table.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        table.setText("Tambah");
        table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableActionPerformed(evt);
            }
        });
        kasir.add(table, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 180, 40));

        txtkode.setEditable(false);
        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        kasir.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 90, 30));

        txtukuran.setEditable(false);
        kasir.add(txtukuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 90, 30));

        nott.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        nott.setText("Buat Nota");
        nott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nottActionPerformed(evt);
            }
        });
        kasir.add(nott, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 180, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Jumlah Bayar :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Kembalian :");

        txtk.setEditable(false);
        txtk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        txtkembali.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtkembali.setText("Kembalian");
        txtkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtkembali)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtkembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        kasir.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 340, 220));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        kasir.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 190));

        mainpanel.add(kasir, "card3");

        lap.setBackground(new java.awt.Color(255, 102, 0));
        lap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setText("Keterangan");
        lap.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel13.setText("Totalan yuk!");
        lap.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        data.setBackground(new java.awt.Color(204, 204, 204));
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode ", "Jumlah", "Ukuran", "harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data.setSelectionForeground(new java.awt.Color(102, 102, 102));
        object1.setViewportView(data);

        lap.add(object1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 140));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel21.setText("No kode dan no ukuran sesuai dengan menu Katalog");
        lap.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        mainpanel.add(lap, "card4");

        nota.setBackground(new java.awt.Color(255, 102, 0));

        area.setBackground(new java.awt.Color(204, 204, 204));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel22.setText("Ini Notanya yah!");

        javax.swing.GroupLayout notaLayout = new javax.swing.GroupLayout(nota);
        nota.setLayout(notaLayout);
        notaLayout.setHorizontalGroup(
            notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notaLayout.createSequentialGroup()
                .addGroup(notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(notaLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(notaLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel22)))
                .addContainerGap(458, Short.MAX_VALUE))
        );
        notaLayout.setVerticalGroup(
            notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel22)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        mainpanel.add(nota, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KatalogActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(kat);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_KatalogActionPerformed

    private void cbukuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbukuranActionPerformed
        // TODO add your handling code here:
           pilihan=(String)cbukuran.getSelectedItem();
        switch (pilihan) {
            case "XS":
                ukuran=1;
            break;
             case "S":
                ukuran=2;
            break;
             case "M":
                ukuran=3;
            break;
             case "L":
                ukuran=4;
            break;
             case "XL":
                ukuran=5;
            break;
        }
txtukuran.setText("Ukuran"+" "+"no"+" "+Integer.toString(ukuran));

    }//GEN-LAST:event_cbukuranActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarActionPerformed

    private void TentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TentangActionPerformed
        // TODO add your handling code here:
        about a =new about();
        a.setVisible(true);
        
    }//GEN-LAST:event_TentangActionPerformed

    private void KasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KasirActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(kasir);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_KasirActionPerformed

    private void LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanActionPerformed
        // TODO add your handling code here:
         mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(lap);
        mainpanel.repaint();
        mainpanel.revalidate();
        
    }//GEN-LAST:event_LaporanActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        katalog1 b=new katalog1();
        b.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        KasirNisa kn=new KasirNisa();
        kn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EXITActionPerformed

    private void txtjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void txtkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkActionPerformed

    private void cbkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkodeActionPerformed
        // TODO add your handling code here:
        pilihan=(String)cbkode.getSelectedItem();
        switch (pilihan) {
            case "Nb A48D":
                   harga_barang =228000;
            break;
            case "Nb A48A":
                    harga_barang =228000;
            break;
            case "Nb A49A":
                    harga_barang =238000;
            break;
            case "Nb A49M":
                    harga_barang =238000;
            break;
            case "Nb A50M":
                    harga_barang =228000;
            break;
            case "Nb A46K":
                    harga_barang =228000;
            break;
            case "Na 40C":
                    harga_barang =148000;
            break;
            case "Na 40A":
                    harga_barang =148000;
            break;        
                
            
        }
txtharga.setText(""+Integer.toString(harga_barang));

        pilihan2=(String)cbkode.getSelectedItem();
        switch (pilihan2) {
            case "Nb A48D":
                    kodbar=1;
            break;
            case "Nb A48A":
                     kodbar=2;
            break;
            case "Nb A49A":
                    kodbar=3;
            break;
            case "Nb A49M":
                    kodbar=4;
            break;
            case "Nb A50M":
                     kodbar=5;
            break;
            case "Nb A46K":
                     kodbar=6;
            case "Na 40C":
                    kodbar=7;
            break;
            case "Na 40A":
                     kodbar=8;
            break;        
                
            
        }
txtkode.setText("katalog"+" "+"ke"+" "+Integer.toString(kodbar));
    }//GEN-LAST:event_cbkodeActionPerformed

    private void cbpcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpcsActionPerformed
        // TODO add your handling code here:
       pilihan=(String)cbpcs.getSelectedItem();
        switch (pilihan) {
            case "1":
                   jumlah_barang =1;
            break;
            case "2":
                   jumlah_barang =2;
            break;
            case "3":
                   jumlah_barang =3;
            break;
            case "4":
                   jumlah_barang =4;
            break;
            case "5":
                   jumlah_barang =5;
            break;
        }
        txtjumlah.setText(""+Integer.toString(jumlah_barang));
    }//GEN-LAST:event_cbpcsActionPerformed

    private void tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah2ActionPerformed
        
harga =Integer.parseInt(txtharga.getText());
beli =Integer.parseInt(txtjumlah.getText());

bayarbrg =harga * beli ;

DecimalFormat angka =new DecimalFormat("###,###");
txtharga.setText("Rp."+Integer.toString(bayarbrg));
// TODO add your handling code here:
    }//GEN-LAST:event_tambah2ActionPerformed

    private void txtkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkembaliActionPerformed
       int kembali =Integer.parseInt(txtbayar.getText());
       int total = kembali -bayarbrg;
       txtk.setText("Rp."+Integer.toString(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkembaliActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
             txtbayar.setText("");
             txtk.setText("");
             cbkode.setSelectedIndex(0);
             cbukuran.setSelectedIndex(0);
             cbpcs.setSelectedIndex(0);
             txtjumlah.setText("");
             txtharga.setText("");
             txtukuran.setText("");
             txtkode.setText("");
    }//GEN-LAST:event_RefreshActionPerformed

    private void tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) data.getModel();
        model.addRow(new Object []{txtkode.getText(),txtjumlah.getText(),txtukuran.getText(),txtharga.getText()});
                
    }//GEN-LAST:event_tableActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    private void nottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nottActionPerformed
        // TODO add your handling code here:
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"*                          *Nisa Collection*                *\n");
        area.setText(area.getText()+"***********************************************\n");
        Date obj =new Date();
        String date =obj.toString();
        
        area.setText(area.getText()+"Kode Barang: "+txtkode.getText()+"\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"Jumlah Barang: "+txtjumlah.getText()+"\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"ukuran Barang: "+txtukuran.getText()+"\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"Harga: "+txtharga.getText()+"\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"Bayar: "+txtbayar.getText()+"\n");
        area.setText(area.getText()+"Kembali: "+txtk.getText()+"\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"***********************************************\n");
        area.setText(area.getText()+"*********TERIMA KASIH SUDAH BELANJA**********\n");
         area.setText(area.getText()+"Keterangan kode dan ukuran sudah ada pada Item :) "+txtk.getText()+"\n");
        
    }//GEN-LAST:event_nottActionPerformed

    private void NotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaActionPerformed
        // TODO add your handling code here:
        mainpanel.removeAll();
        mainpanel.repaint();
        mainpanel.revalidate();
        
        mainpanel.add(nota);
        mainpanel.repaint();
        mainpanel.revalidate();
    }//GEN-LAST:event_NotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(katalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new katalog(nama).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton Kasir;
    private javax.swing.JButton Katalog;
    private javax.swing.JButton Laporan;
    private javax.swing.JButton Nota;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Tentang;
    private javax.swing.JTextArea area;
    private javax.swing.JComboBox<String> cbkode;
    private javax.swing.JComboBox<String> cbpcs;
    private javax.swing.JComboBox<String> cbukuran;
    public javax.swing.JTable data;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kasir;
    private javax.swing.JPanel kat;
    private javax.swing.JPanel lap;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JLabel nisa;
    private javax.swing.JPanel nota;
    private javax.swing.JButton nott;
    javax.swing.JScrollPane object1;
    private javax.swing.JButton table;
    private javax.swing.JButton tambah2;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtk;
    private javax.swing.JButton txtkembali;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtukuran;
    // End of variables declaration//GEN-END:variables
}
