/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS;

/**
 *
 * @author ASUS
 */
public class katalog1 extends javax.swing.JFrame {

    /**
     * Creates new form katalog
     */
    public katalog1() {
        initComponents();
            this.setTitle("Katalog");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        katpanel = new javax.swing.JPanel();
        nba48abu = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        nba48dusty = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        nba49abu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nba49maron = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        nba50maron = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nba46khaki = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        na40cap = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        na40abu = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        katpanel.setBackground(new java.awt.Color(255, 102, 0));
        katpanel.setLayout(new java.awt.CardLayout());

        nba48abu.setBackground(new java.awt.Color(255, 102, 0));
        nba48abu.setPreferredSize(new java.awt.Dimension(1006, 641));
        nba48abu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next6.jpg"))); // NOI18N
        nba48abu.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 630));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setText("Gamis Nibra's NB A48 Abu Muda");
        nba48abu.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel27.setText("Bahan Sorento");
        nba48abu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel28.setText("Busui Frendly");
        nba48abu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel29.setText("Lengan Manset dan Kancing");
        nba48abu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel30.setText("Variasi Buck le");
        nba48abu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("IDR XS-XL 228.000");
        nba48abu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("IDR XLL 240.000");
        nba48abu.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        nba48abu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, -1, -1));

        katpanel.add(nba48abu, "card5");

        nba48dusty.setBackground(new java.awt.Color(255, 102, 0));
        nba48dusty.setPreferredSize(new java.awt.Dimension(1013, 660));
        nba48dusty.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel33.setText("Gamis Nibra's NB A48 Dusty Pink");
        nba48dusty.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel34.setText("Bahan Sorento");
        nba48dusty.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel35.setText("Busui Frendly");
        nba48dusty.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel36.setText("Lengan Manset dan Kancing");
        nba48dusty.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel37.setText("Variasi Buck le");
        nba48dusty.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel38.setText("IDR XS-XL 228.000");
        nba48dusty.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel39.setText("IDR XLL 240.000");
        nba48dusty.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setText("NEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        nba48dusty.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next7.jpg"))); // NOI18N
        nba48dusty.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        katpanel.add(nba48dusty, "card9");

        nba49abu.setBackground(new java.awt.Color(255, 102, 0));
        nba49abu.setForeground(new java.awt.Color(255, 102, 0));
        nba49abu.setPreferredSize(new java.awt.Dimension(1013, 660));
        nba49abu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next1.jpg"))); // NOI18N
        nba49abu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 570));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Gamis Nibras NB A49 ABU");
        nba49abu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Bahan Monalisa Mix Cassanova 2D");
        nba49abu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Busui Frendly");
        nba49abu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Lengan Manset dan Kancing");
        nba49abu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Saku Depan");
        nba49abu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("XS-XL IDR 238.000");
        nba49abu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("XXL IDR 250.000");
        nba49abu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        nba49abu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, -1, -1));

        katpanel.add(nba49abu, "card2");

        nba49maron.setBackground(new java.awt.Color(255, 102, 0));
        nba49maron.setPreferredSize(new java.awt.Dimension(1013, 660));
        nba49maron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next2.jpg"))); // NOI18N
        nba49maron.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Gamis Nibra's NB A49 Maroon");
        nba49maron.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel11.setText("Bahan Monalisa Mix Cassanova 2D");
        nba49maron.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setText("Busui Frendly");
        nba49maron.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel13.setText("Lengan Manset dan Kancing");
        nba49maron.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel14.setText("Saku Depan");
        nba49maron.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, 20));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("XS-XL IDR 238.000");
        nba49maron.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("XXL IDR 250.000");
        nba49maron.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        nba49maron.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, -1, -1));

        katpanel.add(nba49maron, "card3");

        nba50maron.setBackground(new java.awt.Color(255, 102, 0));
        nba50maron.setPreferredSize(new java.awt.Dimension(1013, 660));
        nba50maron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next5.jpg"))); // NOI18N
        nba50maron.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 624, 580));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Gamis Nibra's NB A50 Maroon");
        nba50maron.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel19.setText("Bahan  Cassanova 2D");
        nba50maron.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 107, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel22.setText("Busui Frendly");
        nba50maron.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel23.setText("Lengan Manset dan Kancing");
        nba50maron.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel24.setText("Saku Depan");
        nba50maron.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("IDR XLL 240.000");
        nba50maron.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("IDR XS-XL 228.000");
        nba50maron.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, -1, -1));

        katpanel.add(nba50maron, "card4");

        nba46khaki.setBackground(new java.awt.Color(255, 102, 0));
        nba46khaki.setMaximumSize(new java.awt.Dimension(1006, 641));
        nba46khaki.setPreferredSize(new java.awt.Dimension(1013, 660));
        nba46khaki.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next8.jpg"))); // NOI18N
        nba46khaki.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 590));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel42.setText("Gamis Nibra's NB A46 Khaki");
        nba46khaki.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel43.setText("Bahan Cotton Chambray");
        nba46khaki.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel44.setText("Saku Depan");
        nba46khaki.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel45.setText("Variasi Opnaisel Pada Lengan");
        nba46khaki.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel46.setText("IDR XS-XL 228.000");
        nba46khaki.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel47.setText("IDR XLL 240.000");
        nba46khaki.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setText("NEXT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        nba46khaki.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        katpanel.add(nba46khaki, "card7");

        na40cap.setBackground(new java.awt.Color(255, 102, 0));
        na40cap.setPreferredSize(new java.awt.Dimension(1013, 660));
        na40cap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next10.jpg"))); // NOI18N
        na40cap.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 560));

        jLabel57.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel57.setText("Bahan Mosscrepe Stretch");
        na40cap.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel58.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel58.setText("Busui Frendly");
        na40cap.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        jLabel59.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel59.setText("Lengan Manset dan Kancing");
        na40cap.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel60.setText("XS-XL 148.000");
        na40cap.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, -1, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel61.setText("XXL 160.000");
        na40cap.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, -1, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton8.setText("NEXT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        na40cap.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, -1, -1));

        jLabel56.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel56.setText("Atasan Nibra's NA40 Abu Muda");
        na40cap.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        katpanel.add(na40cap, "card9");

        na40abu.setBackground(new java.awt.Color(255, 102, 0));
        na40abu.setPreferredSize(new java.awt.Dimension(1013, 660));
        na40abu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UAS/next9.jpg"))); // NOI18N
        na40abu.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 606, 604));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel48.setText("Atasan Nibra's NA40 Abu Muda");
        na40abu.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel50.setText("Bahan Mosscrepe Stretch");
        na40abu.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel51.setText("XS-XL 148.000");
        na40abu.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel52.setText("XXL 160.000");
        na40abu.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, -1, -1));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel53.setText("Busui Frendly");
        na40abu.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, -1));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel54.setText("Lengan Manset dan Kancing");
        na40abu.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton7.setText("NEXT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        na40abu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        katpanel.add(na40abu, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(katpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(katpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(nba49abu);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(nba49maron);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(na40cap);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(na40abu);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(nba46khaki);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(nba50maron);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         katpanel.removeAll();
        katpanel.repaint();
        katpanel.revalidate();
        
        katpanel.add(nba48abu);
        katpanel.repaint();
        katpanel.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(katalog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(katalog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(katalog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(katalog1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new katalog1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel katpanel;
    private javax.swing.JPanel na40abu;
    private javax.swing.JPanel na40cap;
    private javax.swing.JPanel nba46khaki;
    private javax.swing.JPanel nba48abu;
    private javax.swing.JPanel nba48dusty;
    private javax.swing.JPanel nba49abu;
    private javax.swing.JPanel nba49maron;
    private javax.swing.JPanel nba50maron;
    // End of variables declaration//GEN-END:variables
}
